package model;

public enum TransactionType {
    INITIAL_CAPITAL,
    DELIVERY_INCOME,
    VEHICLE_PURCHASE,
    VEHICLE_SALE,
    VEHICLE_MAINTENANCE,
    ROAD_CONSTRUCTION,
    STOP_CONSTRUCTION,
    OTHER_INCOME,
    OTHER_EXPENSE
}
